# Generated by Django 5.2.7 on 2025-10-24 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identificacion', models.CharField(max_length=20, unique=True)),
                ('NombreCompleto', models.CharField(max_length=100)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('FechaNacimiento', models.DateField(blank=True, null=True)),
                ('ConsentimientoDatos', models.BooleanField(default=True)),
                ('SaludBasica', models.TextField(blank=True, null=True)),
                ('NotaOpcional', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('PesoCorporal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('MedidasCorporales', models.TextField(blank=True, null=True)),
                ('IMC', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('SocioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
        ),
    ]
