# Generated by Django 5.2.7 on 2025-11-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='Password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
