# Generated by Django 5.2.7 on 2025-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='Rol',
            field=models.CharField(default='Socio', max_length=20),
        ),
    ]
