# Generated by Django 5.2.8 on 2025-11-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_socio_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='Altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura en metros', max_digits=4, null=True),
        ),
    ]
