# Generated by Django 5.2.7 on 2025-10-24 23:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('seguridad', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiaSemana', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('TipoComida', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dia_comida',
                'ordering': ['PlanNutricionalID', 'DiaSemana'],
            },
        ),
        migrations.CreateModel(
            name='DiaRutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiaSemana', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('Series', models.PositiveIntegerField(blank=True, null=True)),
                ('Repeticiones', models.PositiveIntegerField(blank=True, null=True)),
                ('Tempo', models.CharField(blank=True, max_length=10, null=True)),
                ('PesoObjetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'db_table': 'dia_rutina_ejercicio',
                'ordering': ['RutinaID', 'DiaSemana'],
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('PorcionBase', models.CharField(blank=True, max_length=50, null=True)),
                ('Kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('Macros', models.TextField(blank=True, null=True)),
                ('Version', models.PositiveIntegerField(default=1)),
                ('FechaVersion', models.DateTimeField(blank=True, null=True)),
                ('UsuarioVersionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentos_versionados', to='seguridad.usuario')),
            ],
            options={
                'db_table': 'alimento',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHoraEntrada', models.DateTimeField()),
                ('FechaHoraSalida', models.DateTimeField(blank=True, null=True)),
                ('TerminalAcceso', models.CharField(blank=True, max_length=50, null=True)),
                ('SocioMembresiaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='pagos.sociomembresia')),
            ],
            options={
                'db_table': 'asistencia',
                'ordering': ['-FechaHoraEntrada'],
            },
        ),
        migrations.CreateModel(
            name='ComidaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Porcion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('Cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('AlimentoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_comidas', to='control_acceso.alimento')),
                ('DiaComidaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='control_acceso.diacomida')),
            ],
            options={
                'db_table': 'comida_alimento',
                'ordering': ['DiaComidaID'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaEjecucion', models.DateField()),
                ('PesoEfectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('SeriesEfectivas', models.PositiveIntegerField(blank=True, null=True)),
                ('RPE', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('Notas', models.TextField(blank=True, null=True)),
                ('DiaRutinaEjercicioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='control_acceso.diarutinaejercicio')),
            ],
            options={
                'db_table': 'ejecucion_sesion',
                'ordering': ['-FechaEjecucion'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('GrupoMuscular', models.CharField(blank=True, max_length=50, null=True)),
                ('Equipo', models.CharField(blank=True, max_length=50, null=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Variantes', models.TextField(blank=True, null=True)),
                ('Version', models.PositiveIntegerField(default=1)),
                ('FechaVersion', models.DateTimeField(blank=True, null=True)),
                ('UsuarioVersionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios_versionados', to='seguridad.usuario')),
            ],
            options={
                'db_table': 'ejercicio',
                'ordering': ['Nombre'],
            },
        ),
        migrations.AddField(
            model_name='diarutinaejercicio',
            name='EjercicioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_rutinas', to='control_acceso.ejercicio'),
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjetivoCaloricoDiario', models.IntegerField(blank=True, null=True)),
                ('SocioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricionales', to='socios.socio')),
            ],
            options={
                'db_table': 'plan_nutricional',
            },
        ),
        migrations.AddField(
            model_name='diacomida',
            name='PlanNutricionalID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_comida', to='control_acceso.plannutricional'),
        ),
        migrations.CreateModel(
            name='RutinaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('DiasEntrenamiento', models.CharField(help_text='Ej: LMXJVSD (Lunes..Domingo) o similar', max_length=7)),
                ('EsPlantilla', models.BooleanField(default=False)),
                ('SocioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='socios.socio')),
            ],
            options={
                'db_table': 'rutina_semanal',
                'ordering': ['-EsPlantilla', 'Nombre'],
            },
        ),
        migrations.AddField(
            model_name='diarutinaejercicio',
            name='RutinaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_ejercicios', to='control_acceso.rutinasemanal'),
        ),
        migrations.AddConstraint(
            model_name='diarutinaejercicio',
            constraint=models.UniqueConstraint(fields=('RutinaID', 'EjercicioID', 'DiaSemana'), name='u_rutina_ejercicio_dia'),
        ),
    ]
