# Generated by Django 5.2.8 on 2025-11-26 06:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acceso', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicio', models.DateTimeField()),
                ('FechaFin', models.DateTimeField(blank=True, null=True)),
                ('DuracionMinutos', models.IntegerField(blank=True, null=True)),
                ('DiaSemana', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('RutinaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='control_acceso.rutinasemanal')),
                ('SocioMembresiaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_entrenamiento', to='pagos.sociomembresia')),
            ],
            options={
                'db_table': 'sesion_entrenamiento',
                'ordering': ['-FechaInicio'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioSesionCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completado', models.BooleanField(default=False)),
                ('DiaRutinaEjercicioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_acceso.diarutinaejercicio')),
                ('SesionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_completados', to='control_acceso.sesionentrenamiento')),
            ],
            options={
                'db_table': 'ejercicio_sesion_completado',
                'unique_together': {('SesionID', 'DiaRutinaEjercicioID')},
            },
        ),
    ]
