# Generated by Django 5.2.8 on 2025-11-26 06:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acceso', '0002_sesionentrenamiento_ejerciciosesioncompletado'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='EsEntrenamientoLibre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='NotasSesion',
            field=models.TextField(blank=True, help_text='Notas sobre qué se hizo en la sesión', null=True),
        ),
        migrations.AlterField(
            model_name='sesionentrenamiento',
            name='RutinaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='control_acceso.rutinasemanal'),
        ),
        migrations.CreateModel(
            name='CompletionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiaSemana', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('Semana', models.CharField(help_text='Formato: YYYY-WW', max_length=7)),
                ('Completado', models.BooleanField(default=True)),
                ('FechaCompletado', models.DateTimeField(auto_now_add=True)),
                ('RutinaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_acceso.rutinasemanal')),
                ('SocioMembresiaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='pagos.sociomembresia')),
            ],
            options={
                'db_table': 'completion_tracking',
                'ordering': ['-FechaCompletado'],
                'unique_together': {('SocioMembresiaID', 'RutinaID', 'DiaSemana', 'Semana')},
            },
        ),
    ]
