# Generated by Django 5.2.7 on 2025-11-30 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_acceso", "0003_sesionentrenamiento_esentrenamientolibre_and_more"),
        ("socios", "0005_registrocomidadiaria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rutinasemanal",
            name="SocioID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rutinas",
                to="socios.socio",
            ),
        ),
    ]
