# Generated by Django 5.2.7 on 2025-10-24 00:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, unique=True)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('DuracionDias', models.IntegerField()),
                ('Beneficios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan de Membresía',
                'verbose_name_plural': 'Planes de Membresía',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='SocioMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('Estado', models.CharField(choices=[('Activa', 'Activa'), ('Morosa', 'Morosa'), ('Expirada', 'Expirada')], default='Activa', max_length=20)),
                ('PlanID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='socio_membresias', to='pagos.planmembresia')),
                ('SocioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='socios.socio')),
            ],
            options={
                'verbose_name_plural': 'Socio Membresías',
                'db_table': 'socio_membresia',
                'ordering': ['-FechaInicio'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('TipoPago', models.CharField(blank=True, max_length=50, null=True)),
                ('FechaPago', models.DateTimeField(default=django.utils.timezone.now)),
                ('ComprobanteID', models.CharField(blank=True, max_length=50, null=True)),
                ('MontoPendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('SocioMembresiaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pagos.sociomembresia')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-FechaPago'],
            },
        ),
        migrations.CreateModel(
            name='AlertaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoAlerta', models.CharField(blank=True, max_length=50, null=True)),
                ('FechaGeneracion', models.DateField(default=django.utils.timezone.localdate)),
                ('VistaEnPanel', models.BooleanField(default=False)),
                ('SocioMembresiaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='pagos.sociomembresia')),
            ],
            options={
                'db_table': 'alerta_pago',
                'ordering': ['-FechaGeneracion'],
            },
        ),
    ]
