# Generated by Django 5.2.7 on 2025-11-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
    ]
