# Generated by Django 5.2.7 on 2025-11-30 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_crear_planes_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociomembresia',
            name='PlanID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio_membresias', to='pagos.planmembresia'),
        ),
    ]
