# Generated by Django 5.2.7 on 2025-10-24 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreRol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreUsuario', models.CharField(max_length=50, unique=True)),
                ('PasswordHash', models.CharField(max_length=255)),
                ('UltimoAcceso', models.DateTimeField(blank=True, null=True)),
                ('RolID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguridad.rol')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHora', models.DateTimeField(auto_now_add=True)),
                ('TipoAccion', models.CharField(max_length=50)),
                ('Detalle', models.TextField()),
                ('UsuarioID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.usuario')),
            ],
        ),
    ]
