# Generated by Django 5.2.7 on 2025-11-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguridad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="Email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
