# Generated by Django 5.2.8 on 2025-11-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_usuario_email'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                setattr(
                    user,
                    'Email',
                    f'user_{user.id}@example.com'
                ) or user.save()
                for user in apps.get_model('seguridad', 'Usuario').objects.filter(Email__isnull=True)
            ],
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
